/**
 * Example
 * The example API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExampleEnum } from './exampleEnum';


export interface ExampleView { 
    name: string;
    status: ExampleEnum;
    tags: Array<string> | null;
    date: string;
}
export namespace ExampleView {
}


