/**
 * Example
 * The example API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ExampleEnum = 'STATUS_1' | 'STATUS_2';

export const ExampleEnum = {
    _1: 'STATUS_1' as ExampleEnum,
    _2: 'STATUS_2' as ExampleEnum
};

